apiVersion: v1
kind: Pod
metadata:
  name: django-pod
  labels:
    app: django
spec:
  containers:
  - name: django
    image: django_app:latest
    imagePullPolicy: IfNotPresent  
    ports:
    - containerPort: 80
    - containerPort: 8080
    env:
    - name: SECRET_KEY
      value: '1djkcolakslLKX'
    - name: DATABASE_URL
      value: postgres://taiga:taiga@10.20.24.242:5432/taiga
    - name: ALLOWED_HOSTS
      value: '*'
