apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-jobs
  namespace: edu-furious-nobel
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: migrate-django
        image: postnikov2017/django_app:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: django-config-v1
        - secretRef:
            name: django-secrets
        command: ["python",  "manage.py", "makemigrations", "--noinput"]
      restartPolicy: Never
  backoffLimit: 4