apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  SECRET_KEY: MW5ja2xjbVNLbGMtc2M1NQ==
  DATABASE_URL: cG9zdGdyZXM6Ly90YWlnYTp0YWlnYUAxOTIuMTY4LjEzNC4xNjY6NTQzMi90YWlnYQ==
